#To backup the data of FHEM, alexa-module config, collectord config
FROM debian:stable

#We need an cron or something like this

#Needed Volumes: fhem data, alexa data, collectord data (should be moved to an folder)
